name: CI/CD
on:
  push:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@8.8.0 --activate
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Build (monorepo)
        run: pnpm -r build
      - name: Lint
        run: pnpm -r lint || true
