name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Optional: Build and push Docker images to Docker Hub or ECR
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #
      # - name: Build and push images
      #   run: |
      #     docker build -t youruser/your-backend:latest -f apps/backend/Dockerfile .
      #     docker build -t youruser/your-frontend:latest -f apps/frontend/Dockerfile .
      #     docker push youruser/your-backend:latest
      #     docker push youruser/your-frontend:latest

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy on EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            cd /path/to/your/app &&
            git pull &&
            docker compose pull &&
            docker compose up -d --build
          '
